{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "public-ip-reflector.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "public-ip-reflector.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "public-ip-reflector.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "public-ip-reflector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "public-ip-reflector.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
